server:
  port: 8088

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbapp
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Spring Boot RESTful API refresher course

manage:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans" # exclude env and beans endpoints

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Spring Boot RESTful API refresher course

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to Spring Boot RESTful API refresher course
